# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        /:title

# Setup
title:            Vince Elizaga
tagline:          'Blog - Projects'
description:      'Embedded Systems. Javascript. Microservices. Internet of Things. Experimental Tech Stuff.'
url:              http://velizaga.com
baseurl:          /

author:
  name:           'Vince Elizaga'
  url:            http://velizaga.com

paginate:         5

collections:
  projects:
    output: true

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/vynci/blog
