# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Vince Elizaga
tagline:          'Blog - Projects'
description:      'A software developer by day, a grease monkey by night.'
url:              http://vinceelizaga.com
baseurl:          /

author:
  name:           'Vince Elizaga'
  url:            http://vinceelizaga.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/vynci/blog
